# General Settings
title: NMS Seventh Fleet
description: "Exploring the secrets of the universe one portal at a time."
baseurl: ""
url: ""
theme: jekyll-theme-midnight
excerpt_separator: <!--more-->
permalink: pretty

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"